version: '3.8'

services:
  # Frontend React application
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://server:5000/api
    depends_on:
      - server

  # Backend Express application
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=your_db_password
      - DB_NAME=ehr_demo
      - DB_PORT=5432
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - db

  # PostgreSQL Database
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_db_password
      - POSTGRES_DB=ehr_demo

volumes:
  postgres_data: